jobs:

#####
# Retrieve DOUG
#####
- name: DOUG
  query-name:
      name: DOUG
      field: data

#####
# Retrieve Library Addresses
#####
- name: ErrorsLib
  query-contract:
    destination: $DOUG
    bin: DOUG
    function: lookup
    data: [ErrorsLib]

- name: TypeUtilsLib
  query-contract:
    destination: $DOUG
    bin: DOUG
    function: lookup
    data: [TypeUtilsLib]

- name: ArrayUtilsLib
  query-contract:
    destination: $DOUG
    bin: DOUG
    function: lookup
    data: [ArrayUtilsLib]

- name: MappingsLib
  query-contract:
    destination: $DOUG
    bin: DOUG
    function: lookup
    data: [MappingsLib]

- name: ERC165Utils
  query-contract:
    destination: $DOUG
    bin: DOUG
    function: lookup
    data: [ERC165Utils]

#####
# Archetype Upgrade
#####
- name: ArchetypeRegistry
  query-contract:
    destination: $DOUG
    bin: DOUG
    function: lookup
    data: [ArchetypeRegistry]

- name: ObjectClassArchetype
  query-contract:
    destination: $ArchetypeRegistry
    bin: ArchetypeRegistry
    function: OBJECT_CLASS_ARCHETYPE

- name: ArchetypeImplementationCurrentLookup
  query-contract:
    destination: $DOUG
    bin: DOUG
    function: lookup
    data: [$ObjectClassArchetype]

- name: ArchetypeVersionBeforeUpgrade
  query-contract:
    destination: $ArchetypeImplementationCurrentLookup
    bin: Archetype
    function: getArtifactVersion

- name: ArchetypeImplementationUpgrade
  deploy:
    contract: DefaultArchetype.bin
    libraries: ErrorsLib:$ErrorsLib, TypeUtilsLib:$TypeUtilsLib, ArrayUtilsLib:$ArrayUtilsLib, MappingsLib:$MappingsLib, ERC165Utils:$ERC165Utils

- name: RegisterArchetypeObjectClass
  call:
    destination: $DOUG
    bin: DOUG
    function: register
    data: [$ObjectClassArchetype, $ArchetypeImplementationUpgrade]

- name: ArchetypeImplementationUpgradeLookup
  query-contract:
    destination: $DOUG
    bin: DOUG
    function: lookup
    data: [$ObjectClassArchetype]

- name: ArchetypeVersionAfterUpgrade
  query-contract:
    destination: $ArchetypeImplementationUpgradeLookup
    bin: Archetype
    function: getArtifactVersion

- name: AssertArchetypeUpgradeRegistered
  assert:
    key: $ArchetypeImplementationUpgradeLookup
    relation: eq
    val: $ArchetypeImplementationUpgrade
