#!/usr/bin/env bash

# ----------------------------------------------------------
# read variables
for var in "$@"
do
  if [[ $var == "--runAPI" ]]; then runAPI=true; fi
  if [[ $var == "--skipChain" ]]; then skipChain=true; fi
done

# ----------------------------------------------------------
#  variables
if [[ "$CI_PROJECT_DIR" == "" ]]; then
  export CI_PROJECT_DIR=`pwd`
fi

export NODE_ENV=${NODE_ENV:-"production"}
export API_ABI_DIRECTORY_LOCAL=${API_ABI_DIRECTORY_LOCAL:-"$CI_PROJECT_DIR/api/public-abi"}
export CONTRACTS_DIRECTORY=${CONTRACTS_DIRECTORY:-"$CI_PROJECT_DIR/contracts/src"}
export WEBAPP_NAME=${WEBAPP_NAME:-"Monax Application"}
export WEBAPP_EMAIL=${WEBAPP_EMAIL:-"help@$org_url"}
export CHAIN_SOURCE_DIRECTORY=$CI_PROJECT_DIR/test/chain
export CONTRACTS_DEPLOYMENT_ADDRESS="F390C8CA854874472CAD38C0135F78097BCB632D"


