#!/usr/bin/env bash

set -e

main() {
    cd "$(dirname "${BASH_SOURCE[0]}")/src"

    build_file="build.yaml"
    [[ -z "$1" ]] || build_file="build-$1.yaml"

    echo "Building contract suite from $(readlink -f "$build_file")"

    burrow deploy --file="$build_file"

    cp ../abi.csv ./bin/.

    exit 0
}

main $@
