#!/usr/bin/env bash

set -e

main() {
    build_file="build.yaml"
    [[ -z "$1" ]] || build_file="build-$1.yaml"

    CONTRACTS_DIRECTORY=${CONTRACTS_DIRECTORY:-"$(dirname "${BASH_SOURCE[0]}")/src"}
    cd "$CONTRACTS_DIRECTORY"

    echo "Building contract suite from $build_file"

    burrow deploy --file="$build_file"

    cp ../abi.csv ./bin/.

    exit 0
}

main $@
