#!/usr/bin/env bash

set -e

build_file="build.yaml"
[[ -z "$1" ]] || build_file="build-$1.yaml"

CONTRACTS_DIRECTORY=${CONTRACTS_DIRECTORY:-"$(dirname "${BASH_SOURCE[0]}")"}
cd "$CONTRACTS_DIRECTORY/src"

echo "Building contract suite from $build_file"

burrow deploy "$build_file"

cp ../abi.csv ./bin/.
