#!/usr/bin/env bash

API_ABI_DIRECTORY_LOCAL="./api/public-abi"
CONTRACTS_DIRECTORY=${CONTRACTS_DIRECTORY:-"$(dirname "${BASH_SOURCE[0]}")/src"}
cd "$CONTRACTS_DIRECTORY"

echo
echo "#### Copying public ABIs to $API_ABI_DIRECTORY_LOCAL"
set +e
mkdir -p $API_ABI_DIRECTORY_LOCAL
while read -r abi; do
    cmd="cp $CONTRACTS_DIRECTORY/bin/$abi.bin $API_ABI_DIRECTORY_LOCAL/$abi.bin"
    echo "### $cmd"
    ${cmd}
done < ./contracts/abi.csv
set -e
