#!/usr/bin/env bash

API_ABI_DIRECTORY=${API_ABI_DIRECTORY:-"./api/public-abi"}
CONTRACTS_DIRECTORY=${CONTRACTS_DIRECTORY:-"$(dirname "${BASH_SOURCE[0]}")"}

echo
echo "#### Copying public ABIs to $API_ABI_DIRECTORY"
set +e
mkdir -p $API_ABI_DIRECTORY
while read -r abi; do
cmd="cp $CONTRACTS_DIRECTORY/src/bin/$abi.bin $API_ABI_DIRECTORY/$abi.bin"
    echo "### $cmd"
    ${cmd}
done < "$CONTRACTS_DIRECTORY/abi.csv"
set -e
