#!/usr/bin/env bash

set -e

CHAIN_URL_GRPC=${CHAIN_URL_GRPC:-localhost:10997}
CONTRACTS_DEPLOYMENT_ADDRESS=${CONTRACTS_DEPLOYMENT_ADDRESS:-F390C8CA854874472CAD38C0135F78097BCB632D}

echo -e "Deploying contract suite using Deployment Address: $CONTRACTS_DEPLOYMENT_ADDRESS"
echo -e "Using chain url: $CHAIN_URL_GRPC"

deploy_file="deploy.yaml"
[[ -z "$1" ]] || deploy_file="deploy-$1.yaml"

CONTRACTS_DIRECTORY=${CONTRACTS_DIRECTORY:-"$(dirname "${BASH_SOURCE[0]}")"}
cd "$CONTRACTS_DIRECTORY/src"

echo "Deploying contract suite from $deploy_file"

burrow deploy \
 --chain-url="$CHAIN_URL_GRPC" \
 --mempool-signing="true" \
 --address="$CONTRACTS_DEPLOYMENT_ADDRESS" \
 --timeout=15 \
 --file="$deploy_file"
