jobs:

#####
# Libraries
#####

- name: ErrorsLib
  deploy:
    contract: ErrorsLib.bin

- name: TypeUtilsLib
  deploy:
    contract: TypeUtilsLib.bin

- name: ArrayUtilsLib
  deploy:
    contract: ArrayUtilsLib.bin

- name: MappingsLib
  deploy:
    contract: MappingsLib.bin
    libraries: TypeUtilsLib:$TypeUtilsLib, ArrayUtilsLib:$ArrayUtilsLib

- name: DataStorageUtils
  deploy:
    contract: DataStorageUtils.bin
    libraries: ErrorsLib:$ErrorsLib, MappingsLib:$MappingsLib, TypeUtilsLib:$TypeUtilsLib

- name: ERC165Utils
  deploy:
    contract: ERC165Utils.bin

- name: BpmModelLib
  deploy:
    contract: bpm-model/BpmModelLib.sol
    libraries: ErrorsLib:$ErrorsLib, DataStorageUtils:$DataStorageUtils

- name: BpmRuntimeLib
  deploy:
    contract: bpm-runtime/BpmRuntimeLib.sol
    libraries: ErrorsLib:$ErrorsLib, TypeUtilsLib:$TypeUtilsLib, ArrayUtilsLib:$ArrayUtilsLib, MappingsLib:$MappingsLib, ERC165Utils:$ERC165Utils

- name: AgreementsAPI
  deploy:
    contract: AgreementsAPI.bin
    libraries: ERC165Utils:$ERC165Utils

#####
# Static Data
#####
- name: DataTypesAccess
  deploy:
    contract: DataTypesAccess.bin

#####
# Main Contract (DOUG) + DougProxy
#####

# Implementation
- name: DefaultArtifactsRegistry
  deploy:
    contract: DefaultArtifactsRegistry.bin
    libraries: ErrorsLib:$ErrorsLib

# Proxy contract
- name: ArtifactsRegistry
  deploy:
    contract: OwnedDelegateUnstructuredProxy.bin
    libraries: ErrorsLib:$ErrorsLib
    data: [$DefaultArtifactsRegistry]

- name: InitializeArtifactsRegistryThroughProxy
  call:
    destination: $ArtifactsRegistry
    bin: DefaultArtifactsRegistry
    function: initialize

# Implementation
- name: DefaultDoug
  deploy:
    contract: DefaultDoug.bin
    libraries: ErrorsLib:$ErrorsLib, ArrayUtilsLib:$ArrayUtilsLib, MappingsLib:$MappingsLib, ERC165Utils:$ERC165Utils

# Proxy contract
- name: DOUG
  deploy:
    contract: DougProxy.bin
    libraries: ErrorsLib:$ErrorsLib
    data: [$DefaultDoug]

- name: ChangeArtifactsRegistrySystemOwnerShip
  call:
    destination: $ArtifactsRegistry
    bin: DefaultArtifactsRegistry
    function: transferSystemOwnership
    data: [$DOUG]

- name: SetArtifactsRegistryInDoug
  call:
    destination: $DOUG
    bin: DefaultDoug
    function: setArtifactsRegistry
    data: [$ArtifactsRegistry]

- name: GetArtifactsRegistryFromProxy
  query-contract:
    destination: $DOUG
    bin: DefaultDoug
    function: getArtifactsRegistry

- name: AssertArtifactsRegistryInProxy
  assert:
    key: $GetArtifactsRegistryFromProxy
    relation: eq
    val: $ArtifactsRegistry

# Here we add the proxy contract to the name registry
- name: addDougToNameRegistry
  register:
    name: DOUG
    data: $DOUG
    amount: 5000
    fee: 2000

- name: registerErrorsLibrary
  call:
    destination: $DOUG
    bin: DefaultDoug
    function: register
    data: [ErrorsLib, $ErrorsLib]

- name: registerTypeUtilsLibrary
  call:
    destination: $DOUG
    bin: DefaultDoug
    function: register
    data: [TypeUtilsLib, $TypeUtilsLib]

- name: registerArrayUtilsLibrary
  call:
    destination: $DOUG
    bin: DefaultDoug
    function: register
    data: [ArrayUtilsLib, $ArrayUtilsLib]

- name: registerMappingsLibrary
  call:
    destination: $DOUG
    bin: DefaultDoug
    function: register
    data: [MappingsLib, $MappingsLib]

- name: registerDataStorageUtilsLibrary
  call:
    destination: $DOUG
    bin: DefaultDoug
    function: register
    data: [DataStorageUtils, $DataStorageUtils]

- name: registerERC165UtilsLibrary
  call:
    destination: $DOUG
    bin: DefaultDoug
    function: register
    data: [ERC165Utils, $ERC165Utils]

- name: registerBpmModelLibrary
  call:
    destination: $DOUG
    bin: DefaultDoug
    function: register
    data: [BpmModelLib, $BpmModelLib]

- name: registerBpmRuntimeLibrary
  call:
    destination: $DOUG
    bin: DefaultDoug
    function: register
    data: [BpmRuntimeLib, $BpmRuntimeLib]

- name: registerAgreementsApiLibrary
  call:
    destination: $DOUG
    bin: DefaultDoug
    function: register
    data: [AgreementsAPI, $AgreementsAPI]
