
##########
# Libraries
jobs:

- name: ErrorsLib
  deploy:
    contract: ErrorsLib.bin

- name: TypeUtilsLib
  deploy:
    contract: TypeUtilsLib.bin

- name: ArrayUtilsLib
  deploy:
    contract: ArrayUtilsLib.bin

- name: MappingsLib
  deploy:
    contract: MappingsLib.bin
    libraries: TypeUtilsLib:$TypeUtilsLib, ArrayUtilsLib:$ArrayUtilsLib

- name: ERC165Utils
  deploy:
    contract: ERC165Utils.bin

##########
# DelegateProxy Test
############################################################################################
- name: DelegateProxyTest
  deploy:
    contract: DelegateProxyTest.bin
    libraries: ErrorsLib:$ErrorsLib, TypeUtilsLib:$TypeUtilsLib

- name: testDelegateCallReturns
  call:
    destination: $DelegateProxyTest
    bin: DelegateProxyTest
    function: testDelegateCallReturns

- name: assertDelegateCallReturns
  assert:
    key: $testDelegateCallReturns
    relation: eq
    val: success

##########
# Upgradeable Test
############################################################################################
- name: UpgradeableTest
  deploy:
    contract: UpgradeableTest.bin
    libraries: ErrorsLib:$ErrorsLib

- name: runUpgradeTest
  call:
    destination: $UpgradeableTest
    bin: UpgradeableTest
    function: testUpgrade

- name: assertUpgradeTest
  assert:
    key: $runUpgradeTest
    relation: eq
    val: success

##########
# ArtifactsRegistry Test
############################################################################################
- name: ArtifactsRegistryTest
  deploy:
    contract: ArtifactsRegistryTest.bin
    instance: ArtifactsRegistryTest
    libraries: ErrorsLib:$ErrorsLib, MappingsLib:$MappingsLib, ERC165Utils:$ERC165Utils

- name: testArtifactsRegistry
  call:
    destination: $ArtifactsRegistryTest
    bin: ArtifactsRegistryTest
    function: testArtifactsRegistry

- name: assertArtifactsRegistry
  assert:
    key: $testArtifactsRegistry
    relation: eq
    val: success

#####
# DOUG Test
############################################################################################
- name: DougTest
  deploy:
    contract: DougTest.bin
    instance: DougTest
    libraries: ErrorsLib:$ErrorsLib, ArrayUtilsLib:$ArrayUtilsLib, MappingsLib:$MappingsLib, ERC165Utils:$ERC165Utils

- name: testRegistration
  call:
    destination: $DougTest
    bin: DougTest
    function: testRegistration

- name: assertRegistration
  assert:
    key: $testRegistration
    relation: eq
    val: success

- name: testDeployment
  call:
    destination: $DougTest
    bin: DougTest
    function: testDeployment

- name: assertDeployment
  assert:
    key: $testDeployment
    relation: eq
    val: success

#####
# DougProxyTest
############################################################################################
- name: DougProxyTest
  deploy:
    contract: DougProxyTest.bin
    instance: DougProxyTest
    libraries: ErrorsLib:$ErrorsLib, ArrayUtilsLib:$ArrayUtilsLib, MappingsLib:$MappingsLib, ERC165Utils:$ERC165Utils

- name: testProxyDelegation
  call:
    destination: $DougProxyTest
    bin: DougProxyTest
    function: testProxyDelegation

- name: assertProxyDelegation
  assert:
    key: $testProxyDelegation
    relation: eq
    val: success


#####
# ObjectProxyTest
############################################################################################
- name: ObjectProxyTest
  deploy:
    contract: ObjectProxyTest.bin
    instance: ObjectProxyTest
    libraries: ErrorsLib:$ErrorsLib, ArrayUtilsLib:$ArrayUtilsLib, TypeUtilsLib:$TypeUtilsLib, MappingsLib:$MappingsLib, ERC165Utils:$ERC165Utils

- name: testProxyHandling
  call:
    destination: $ObjectProxyTest
    bin: ObjectProxyTest
    function: testProxyHandling

- name: assertProxyHandling
  assert:
    key: $testProxyHandling
    relation: eq
    val: success


#####
# DOUG + Proxy setup via EPM (This tests the typical EPM DOUG setup in projects)
############################################################################################
- name: DefaultArtifactsRegistry
  deploy:
    contract: DefaultArtifactsRegistry.bin
    libraries: ErrorsLib:$ErrorsLib

# Proxy contract
- name: ArtifactsRegistry
  deploy:
    contract: OwnedDelegateUnstructuredProxy.bin
    libraries: ErrorsLib:$ErrorsLib
    data: [$DefaultArtifactsRegistry]

- name: InitializeArtifactsRegistryThroughProxy
  call:
    destination: $ArtifactsRegistry
    bin: DefaultArtifactsRegistry
    function: initialize

- name: DefaultDoug
  deploy:
    contract: DefaultDoug.bin
    libraries: ErrorsLib:$ErrorsLib, ArrayUtilsLib:$ArrayUtilsLib, MappingsLib:$MappingsLib, ERC165Utils:$ERC165Utils

# proxy contract
- name: DOUG
  deploy:
    contract: DougProxy.bin
    libraries: ErrorsLib:$ErrorsLib
    data: [$DefaultDoug]

# this enables DOUG to use the ArtifactsRegistry!
- name: ChangeArtifactsRegistrySystemOwnerShip
  call:
    destination: $ArtifactsRegistry
    bin: DefaultArtifactsRegistry
    function: transferSystemOwnership
    data: [$DOUG]

- name: SetArtifactsRegistryInDoug
  call:
    destination: $DOUG
    bin: DefaultDoug
    function: setArtifactsRegistry
    data: [$ArtifactsRegistry]


